name = "kimi-groq-proxy"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "kimi-groq-proxy"

[env.staging]
name = "kimi-groq-proxy-staging"

# Environment variables (configure these via wrangler secret put)
# GROQ_API_KEY (required)

# Build handled by wrangler automatically